spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kuckjwi
    username: kcukjwi
    password: kuckjwi
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: "classpath:schema.sql"
      data-locations: "classpath:data.sql"

graphql:
  servlet:
    mapping: /graphql